# Goal (The angle that we need to increment and send feedback with) 
float64 angle

---

# Result (Directory at which the screenshots are taken)
string directory

---

# Feedback (Incrementer -> percentage, URL -> Link to the screenshot)
float64 incrementer
string url