# camera1:
#   index: '/dev/stereo_left'
#   width: 640
#   height: 480
#   fps: 20
#   port: 8081
# camera2:
#   index: /dev/stereo_right
#   width: 640
#   height: 480
#   fps: 30
#   port: 8082
# camera3:
#   index: '/dev/rapoo_camera'
#   width: 1280
#   height: 960
#   fps: 20
#   port: 8083
camera3:
  index: '/dev/video1'
  width: 1280
  height: 720
  fps: 20
  port: 8081
camera4:
  index: '/dev/video8'
  width: 640
  height: 480
  fps: 20
  port: 8082
camera5:
  index: '/dev/video16'
  width: 1280
  height: 720
  fps: 20
  port: 8084

#Rapoo and left cameras probably doesnt not suppoer mjpg format