camera1:
  index: '/dev/stereo_camera'
  width: 340
  height: 240
  fps: 20
  port: 8081
camera2:
  index: /dev/fisheye_camera
  width: 320
  height: 240
  fps: 30
  port: 8082
camera3:
  index: '/dev/rapoo_camera'
  width: 640
  height: 480
  fps: 20
  port: 8083
camera4:
  index: '/dev/logitech_camera_2'
  width: 320
  height: 240
  fps: 30
  port: 8084
# camera5:
#   index: '/dev/logitech_camera_2'
#   width: 1280
#   height: 720
#   fps: 15
#   port: 8081
# camera5:
#   index: '/dev/video8'
#   width: 1280
#   height: 720
#   format: MJPG
#   type: NORMAL
#   fps: 20
#   port: 8081
horizontal_gripper_camera:
  index: /dev/logitech_camera1
  width: 640
  height: 480
  format: MJPG
  type: NORMAL
  fps: 30
  port: 8082
vertical_gripper_camera:
  index: /dev/logitech_camera2
  width: 640
  height: 480
  format: MJPG
  type: NORMAL
  fps: 30
  port: 8083
photosphere:
  index: /dev/fisheye_camera
  width: 640
  height: 480
  format: MJPG
  type: FISHEYE
  fps: 30
  port: 8084
stereo:
  index: /dev/stereo_camera
  focal_length: 3 #mm
  baseline: 12 #cm
  width: 1280
  height: 480
  format: MJPG
  type: STEREO
  fps: 30
left_stereo:
  index: /dev/stereo_left #--> video17
  width: 640
  height: 480
  format: MJPG
  type: NORMAL
  fps: 30
  port: 8085
right_stereo:
  index: /dev/stereo_right  #--> video18
  width: 640
  height: 480
  format: MJPG
  type: NORMAL
  fps: 30
  port: 8086
stitched:
  index: /dev/stereo_stitched #--> video19
  width: 1280
  height: 480
  format: MJPG
  type: STITCHED
  fps: 30
  port: 8087


# # #Rapoo and left cameras probably doesnt not suppoer mjpg format