camera1:
  index: '/dev/left_camera'
  width: 480
  height: 360
  fps: 30
  port: 8080
camera2:
  index: '/dev/right_camera'
  width: 480
  height: 360
  fps: 30
  port: 8081
camera3:
  index: '/dev/rapoo_camera'
  width: 480
  height: 360
  fps: 30
  port: 8082