#IT IS DESTINED FOR WHOMEVER MESSES THE HASH INDENTATION TO HAVE A LONG LIFE OF SUFFERING AND MISREY!

#----- THRUSTERS ---------------#
FRONT_RIGHT_PCA_CHANNEL: 5
FRONT_LEFT_PCA_CHANNEL: 1
BACK_LEFT_PCA_CHANNEL: 4
BACK_RIGHT_PCA_CHANNEL: 0
FRONT_PCA_CHANNEL: 3
BACK_PCA_CHANNEL: 2
#----- LEFT GRIPPER ------------#
DC_LEFT_GPIO: 7
DC_LEFT_PCA_CHANNEL: 8
LEFT_GRIPPER_SWITCH: 16
#------ RIGHT GRIPPER ----------#
DC_RIGHT_GPIO: 21
DC_RIGHT_PCA_CHANNEL: 9
RIGHT_GRIPPER_SWITCH: 12
#------ FLASH ------------------#
FLASH_SWITCH: 20