#LEFTSIDE
button_l1: LEFTGRIPPER_UP_DOWN #SWITCHING
button_l2: LEFTGRIPPER  #SWITCHING
button_left: LEFTGRIPPER_UP_CLOSE
button_right: LEFTGRIPPER_UP_OPEN 
button_share: PHOTOSPHERE_SERVO_LEFT
button_options: PHOTOSPHERE_SERVO_RIGHT

#RIGHTSIDE
button_r1: VERTICALGRIPPER_LEFT_RIGHT
button_r2: VERTICALGRIPPER #SWITCHING

#FRONTSIDE
button_x: FRONTGRIPPER
button_bot: STEREO_SERVO_DOWN
button_top: STEREO_SERVO_UP
button_o:  DCFRONTGRIPPER_RIGHT
button_rect: DCFRONTGRIPPER_LEFT 

#BACKSIDE
button_tri: SYRINGE #SWITCHING

#MISC
button_l3: HEAVE_DOWN
button_r3: HEAVE_UP