button_bot: SERVO_DOWN
button_l1: LEFTGRIPPER_OPEN
button_l2: LEFTGRIPPER_CLOSE
button_l3: HEAVE_DOWN
button_left: DCLEFTGRIPPER_RIGHT
button_o: DCRIGHTGRIPPER_RIGHT
button_r1: RIGHTGRIPPER
button_r2: LEFTGRIPPER
button_r3: HEAVE_UP
button_rect: DCRIGHTGRIPPER_LEFT
button_right: DCLEFTGRIPPER_LEFT
button_top: SERVO_UP
button_tri: bty5
button_x: FLASH
