w: 
  axis: x
  direction: 1.0
s: 
  axis: x
  direction: -1.0
a: 
  axis: y
  direction: -1.0
d: 
  axis: y
  direction: 1.0
p: 
  axis: z
  direction: 1.0
r: 
  axis: z
  direction: -1.0
f: 
  axis: yaw
  direction: 1.0
h: 
  axis: yaw
  direction: -1.0
t: 
  axis: pitch
  direction: 1.0
g: 
  axis: pitch
  direction: -1.0

